// Authentication utilities for Employee Happiness Radar

// Admin invite tokens (in real app, these would be generated by backend)
const ADMIN_INVITE_TOKENS = [
  {
    token: 'ADMIN-INVITE-2025-MAIN',
    expiresAt: new Date('2026-12-31').getTime(),
    used: false,
    description: 'Main Admin Token'
  },
  {
    token: 'ADMIN-INVITE-HR-001',
    expiresAt: new Date('2026-12-31').getTime(),
    used: false,
    description: 'HR Department Token'
  },
  {
    token: 'ADMIN-INVITE-EXEC-001',
    expiresAt: new Date('2026-12-31').getTime(),
    used: false,
    description: 'Executive Token'
  }
];

// Initialize tokens in localStorage
export const initializeTokens = () => {
  const stored = localStorage.getItem('admin_invite_tokens');
  if (!stored) {
    localStorage.setItem('admin_invite_tokens', JSON.stringify(ADMIN_INVITE_TOKENS));
  }
};

// Validate admin invite token
export const validateInviteToken = (token) => {
  const tokens = JSON.parse(localStorage.getItem('admin_invite_tokens') || '[]');
  const foundToken = tokens.find(t => t.token === token);
  
  if (!foundToken) {
    return { valid: false, message: 'Invalid invite token' };
  }
  
  if (foundToken.used) {
    return { valid: false, message: 'Token has already been used' };
  }
  
  if (foundToken.expiresAt < Date.now()) {
    return { valid: false, message: 'Token has expired' };
  }
  
  return { valid: true, message: 'Token is valid' };
};

// Mark token as used
export const markTokenAsUsed = (token) => {
  const tokens = JSON.parse(localStorage.getItem('admin_invite_tokens') || '[]');
  const updatedTokens = tokens.map(t => 
    t.token === token ? { ...t, used: true } : t
  );
  localStorage.setItem('admin_invite_tokens', JSON.stringify(updatedTokens));
};

// Generate new admin invite token (only main admin can do this)
export const generateInviteToken = (description) => {
  const tokens = JSON.parse(localStorage.getItem('admin_invite_tokens') || '[]');
  const newToken = {
    token: `ADMIN-INVITE-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).getTime(), // 30 days
    used: false,
    description: description || 'Generated Token'
  };
  tokens.push(newToken);
  localStorage.setItem('admin_invite_tokens', JSON.stringify(updatedTokens => [...tokens]));
  return newToken.token;
};

// Check if user is authenticated admin
export const isAdminAuthenticated = () => {
  const token = localStorage.getItem('hr_admin_token');
  const admin = localStorage.getItem('hr_admin');
  return !!(token && admin);
};

// Check if user is authenticated employee
export const isEmployeeAuthenticated = () => {
  const token = localStorage.getItem('hr_employee_token');
  const employee = localStorage.getItem('hr_employee');
  return !!(token && employee);
};

// Admin login
export const adminLogin = (email, password) => {
  const admins = JSON.parse(localStorage.getItem('hr_admins') || '[]');
  const admin = admins.find(a => a.email === email && a.password === password);
  
  if (!admin) {
    return { success: false, message: 'Invalid credentials' };
  }
  
  // Generate JWT-like token (simulated)
  const token = `admin_${btoa(email)}_${Date.now()}`;
  
  localStorage.setItem('hr_admin_token', token);
  localStorage.setItem('hr_admin', JSON.stringify({
    id: admin.id,
    name: admin.name,
    email: admin.email,
    role: admin.role || 'admin'
  }));
  
  return { success: true, token, admin: { ...admin, password: undefined } };
};

// Admin signup
export const adminSignup = (name, email, password, inviteToken) => {
  // Validate invite token
  const validation = validateInviteToken(inviteToken);
  if (!validation.valid) {
    return { success: false, message: validation.message };
  }
  
  // Check if admin already exists
  const admins = JSON.parse(localStorage.getItem('hr_admins') || '[]');
  if (admins.find(a => a.email === email)) {
    return { success: false, message: 'Admin with this email already exists' };
  }
  
  // Create new admin
  const newAdmin = {
    id: `admin_${Date.now()}`,
    name,
    email,
    password, // In real app, this would be hashed
    createdAt: Date.now(),
    role: 'admin'
  };
  
  admins.push(newAdmin);
  localStorage.setItem('hr_admins', JSON.stringify(admins));
  
  // Mark token as used
  markTokenAsUsed(inviteToken);
  
  return { success: true, message: 'Admin account created successfully' };
};

// Employee login
export const employeeLogin = (email, password) => {
  const employees = JSON.parse(localStorage.getItem('hr_employees') || '[]');
  const employee = employees.find(e => e.email === email && e.password === password);
  
  if (!employee) {
    return { success: false, message: 'Invalid credentials' };
  }
  
  // Generate JWT-like token (simulated)
  const token = `employee_${btoa(email)}_${Date.now()}`;
  
  localStorage.setItem('hr_employee_token', token);
  localStorage.setItem('hr_employee', JSON.stringify({
    id: employee.id,
    name: employee.name,
    email: employee.email,
    department: employee.department
  }));
  
  return { success: true, token, employee: { ...employee, password: undefined } };
};

// Employee signup
export const employeeSignup = (name, email, password, department) => {
  const employees = JSON.parse(localStorage.getItem('hr_employees') || '[]');
  
  if (employees.find(e => e.email === email)) {
    return { success: false, message: 'Employee with this email already exists' };
  }
  
  const newEmployee = {
    id: `emp_${Date.now()}`,
    name,
    email,
    password, // In real app, this would be hashed
    department,
    createdAt: Date.now(),
    lastLogin: null,
    streak: 0,
    lastCheckIn: null
  };
  
  employees.push(newEmployee);
  localStorage.setItem('hr_employees', JSON.stringify(employees));
  
  return { success: true, message: 'Employee account created successfully' };
};

// Logout functions
export const adminLogout = () => {
  localStorage.removeItem('hr_admin_token');
  localStorage.removeItem('hr_admin');
};

export const employeeLogout = () => {
  localStorage.removeItem('hr_employee_token');
  localStorage.removeItem('hr_employee');
};

// Get current admin
export const getCurrentAdmin = () => {
  const admin = localStorage.getItem('hr_admin');
  return admin ? JSON.parse(admin) : null;
};

// Get current employee
export const getCurrentEmployee = () => {
  const employee = localStorage.getItem('hr_employee');
  return employee ? JSON.parse(employee) : null;
};
